config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

from dogs.views import index_view, BreedsListView, DogBreedListView, DogListView, DogCreateView, \
    DogDetailView, DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, BreedDogSearchListView, DogSearchListView, BreedSearchListView

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', cache_page(1)(index_view), name='index'),
    path('breeds/', cache_page(1)(BreedsListView.as_view()), name='breeds'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breed_search'),
    path('breeds/search_all/', BreedDogSearchListView.as_view(), name='breed_dog_search'),

    # dogs
    path('breeds/<int:pk>/dogs', DogBreedListView.as_view(), name='breed_dogs'),
    path('dogs/', DogListView.as_view(), name='dogs_list'),
    path('dogs/deactivated/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

reviews/urls.py
from django.urls import path
from reviews.apps import ReviewsConfig

from reviews.views import ReviewListView, ReviewDeactivatedListView, ReviewCreateView, ReviewDetailView, ReviewUpdateView, ReviewDeleteView, review_toggle_activity

app_name = ReviewsConfig.name

urlpatterns = [
    path('', ReviewListView.as_view(), name='reviews_list'),
    path('deactivated/', ReviewDeactivatedListView.as_view(), name='reviews_deactivated_list'),
    path('create/', ReviewCreateView.as_view(), name='review_create'),
    path('detail/<slug:slug>/', ReviewDetailView.as_view(), name='review_detail'),
    path('update/<slug:slug>/', ReviewUpdateView.as_view(), name='review_update'),
    path('delete/<slug:slug>/', ReviewDeleteView.as_view(), name='review_delete'),
    path('toggle/<slug:slug>/', review_toggle_activity, name='review_toggle'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from users.models import NULLABLE
from dogs.models import Dog


class Review(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=25, unique=True, db_index=True, verbose_name='URL')
    content = models.TextField(verbose_name='Содержимое')
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    sign_of_review = models.BooleanField(default=True, verbose_name='Активный')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Автор')
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, related_name='dogs', verbose_name='Собака')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('reviews:review_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'

reviews/forms.py
from django import forms
from reviews.models import Review
from users.forms import StyleFormMixin


class ReviewAdminForm(StyleFormMixin, forms.ModelForm):
    title = forms.CharField(max_length=150, label='Заголовок')
    content = forms.TextInput()
    slug = forms.SlugField(max_length=20, initial='temp_slug', widget=forms.HiddenInput)

    class Meta:
        model = Review
        fields = ('dog', 'title', 'content', 'slug')

reviews/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import reverse, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied

from reviews.models import Review
from users.models import UserRoles
from reviews.forms import ReviewAdminForm
from reviews.utils import slug_generator


class ReviewListView(ListView):
    model = Review
    extra_context = {
        'title': 'Все отзывы'
    }
    template_name = 'reviews/reviews.html'
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(sign_of_review=True)


class ReviewDeactivatedListView(ListView):
    model = Review
    extra_context = {
        'title': 'Деактивированные  отзывы'
    }
    template_name = 'reviews/reviews.html'
    paginate_by = 3

    def get_queryset(self):
        return super().get_queryset().filter(sign_of_review=False)


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewAdminForm
    template_name = 'reviews/create_update.html'
    extra_context = {
        'title': 'Добавить отзыв'
    }

    def form_valid(self, form):
        if self.request.user.role not in [UserRoles.USER, UserRoles.ADMIN]:
            return HttpResponseForbidden
        slug_object = form.save()
        print(slug_object.slug)
        if slug_object.slug == 'temp_slug':
            slug_object.slug = slug_generator()
        slug_object.author = self.request.user
        slug_object.save()
        return super().form_valid(form)


class ReviewDetailView(DetailView):
    model = Review
    template_name = 'reviews/detail.html'
    extra_context = {
        'title': 'Просмотр отзыва'
    }


class ReviewUpdateView(LoginRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewAdminForm
    template_name = 'reviews/create_update.html'
    extra_context = {
        'title': 'Изменить отзыв'
    }

    def get_object(self, queryset=None):
        object_ = super().get_object(queryset=queryset)
        if object_.author != self.request.user and self.request.user.role not in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            raise PermissionDenied()
        return object_

    def get_success_url(self):
        return reverse('reviews:review_detail', args=[self.kwargs.get('slug')])


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'reviews/delete.html'
    permission_required = 'reviews.delete_review'

    def get_success_url(self):
        return reverse('reviews:reviews_list')


def review_toggle_activity(request, slug):
    review_item = get_object_or_404(Review, slug=slug)
    if review_item.sign_of_review:
        review_item.sign_of_review = False
        review_item.save()
        return redirect(reverse('reviews:reviews_deactivated_list'))
    else:
        review_item.sign_of_review = True
        review_item.save()
        return redirect(reverse('reviews:reviews_list'))

reviews/templates/reviews/create_update.html
{% extends 'dogs/base.html'%}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактировать отзыв
                {% else %}
                Добавить отзыв
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-outline-success"
                value="{% if object %}Сохранить{% else %}Добавить{% endif %}">
                {% if object %}
                <a href="{ url 'reviews:review_toggle' object.slug %}"
                   class="btn btn-outline-warning float-right">
                    {% if object.sign_of_review %}
                    Деактивировать
                    {% else %}
                    Активировать
                    {% endif %}
                </a>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'reviews:reviews_list' %}" class="btn btn-outline-primary"><< Назад</a>
                {% if object and user.is_superuser %}
                <a href="{% url 'reviews:review_delete' object.slug %}" class="btn btn-outline-danger float-right">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

reviews/templates/reviews/delete.html
{% extends 'dogs/base.html'%}
{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="crd-header">
                {% if object %}
                Вы уверены что хотите удалить отзыв ?
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.title|title }}</p>
                <p class="card-text">{{ object.dog.name|title }}</p>
            </div>
            <div class="card-footer">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger float-right">
                    {% if object %}
                    Удалить
                    {% endif %}
                </button>
                <a href="{% url 'reviews:reviews_list' %}" class="btn btn-outline-primary"><< Назад</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'dogs/base.html'%}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card mb-12 box-shadow">
            <div class="card-header">
                <p class="card-text">
                    Отзыв: {{ object.dog.name }}
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">
                    {{ object.content }}
                </p>
                <span class="text-muted">Дата создания: {{ object.created }}</span><br>
                <span class="text-muted">Автор: {{ object.author|default:"Удаленный пользователь" }}</span>
        </div>
        <div class="card-footer">
            <a href="{% url 'reviews:reviews_list' %}" class="btn btn-outline-primary"><< Назад</a>
        </div>
    </div>
    </div>
</div>
{% endblock %}

reviews/templates/reviews/reviews.html
{% extends 'dogs/base.html'%}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'reviews/includes/inc_review_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
    <a href="{% url 'reviews:review_create'%}" class="btn btn-outline-primary m2 float-left">Добавить отзыв</a>
    <a href="{% url 'reviews:reviews_deactivated_list'%}" class="btn btn-outline-secondary m2 float-right">Неактивные отзывы</a>
    <a href="{% url 'reviews:reviews_list'%}" class="btn btn-outline-success m2 float-left">Активные отзывы</a>
</div>
{% endblock %}