config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

from dogs.views import index_view, BreedsListView, DogBreedListView, DogListView, DogCreateView, \
    DogDetailView, DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, BreedDogSearchListView, DogSearchListView, BreedSearchListView

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', cache_page(1)(index_view), name='index'),
    path('breeds/', cache_page(1)(BreedsListView.as_view()), name='breeds'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breed_search'),
    path('breeds/search_all/', BreedDogSearchListView.as_view(), name='breed_dog_search'),

    # dogs
    path('breeds/<int:pk>/dogs', DogBreedListView.as_view(), name='breed_dogs'),
    path('dogs/', DogListView.as_view(), name='dogs_list'),
    path('dogs/deactivated/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

dogs/models.py
from django.db import models
from django.conf import settings


from users.models import NULLABLE


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')
    description = models.CharField(max_length=1000, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'


class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='Фотография')
    birth_date = models.DateField(**NULLABLE, verbose_name='Дата рождения')
    is_active = models.BooleanField(default=True, verbose_name='Активность')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Хозяин')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.name} ({self.breed})'

    class Meta:
        verbose_name = 'dog'
        verbose_name_plural = 'dogs'

    def views_count(self):
        self.views += 1
        self.save()


class DogParent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, verbose_name='Кличка родителя')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода родителя')
    birth_day = models.DateField(**NULLABLE, verbose_name='Дата рождения родителя')

    def __str__(self):
        return f'{self.name} ({self.breed})'

    class Meta:
        verbose_name = 'parent'
        verbose_name_plural = 'parents'

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog, DogParent
from users.forms import StyleFormMixin


class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        exclude = ('owner', 'is_active', 'views', )

    def clean_birth_date(self):
        cleaned_data = self.cleaned_data['birth_date']
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 35:
            raise forms.ValidationError('Собака должна быть моложе 35 лет')
        return cleaned_data


class DogAdminForm(DogForm):
    class Meta:
        model = Dog
        exclude = ('is_active',)


class DogParentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = DogParent
        fields = '__all__'

dogs/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from dogs.models import Breed, Dog, DogParent
from dogs.forms import DogForm, DogParentForm, DogAdminForm
from dogs.services import send_views_email
from users.models import UserRoles


def index_view(request):
    context = {
        'object_list': Breed.objects.all()[:3],
        'title': 'Питомник - Главная'
    }
    return render(request, 'dogs/index.html', context=context)


class BreedsListView(ListView):
    model = Breed
    extra_context = {
        'title': 'Все наши породы'
    }
    template_name = 'dogs/breeds.html'
    paginate_by = 3


class BreedSearchListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'dogs/breeds.html'
    extra_context = {
        'title': 'Результат поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Breed.objects.filter(Q(name__icontains=query))
        return object_list


class DogBreedListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {
        'title': 'Собаки выбранной породы'
    }

    def get_queryset(self):
        queryset = super().get_queryset().filter(breed_id=self.kwargs.get('pk'))
        return queryset


class DogListView(ListView):
    model = Dog
    extra_context = {
        'title': 'Питомник - все наши собаки'
    }
    template_name = 'dogs/dogs.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class DogDeactivatedListView(LoginRequiredMixin, ListView):
    model = Dog
    extra_context = {
        'title': 'Питомник - все наши собаки'
    }
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.role in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            queryset = queryset.filter(is_active=False)
        if self.request.user.role == UserRoles.USER:
            queryset = queryset.filter(is_active=False, owner=self.request.user)
        return queryset


class DogSearchListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dog_search_results.html'
    extra_context = {
        'title': 'Результат поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Dog.objects.filter(
            Q(name__icontains=query, is_active=True)
        )
        return object_list


class BreedDogSearchListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'dogs/breed_dog_search_results.html'
    extra_context = {
        'title': 'Результаты поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        dog_object_list = Dog.objects.filter(
            Q(name__icontains=query, is_active=True)
        )
        breed_object_list = Breed.objects.filter(
            Q(name__icontains=query)
        )
        object_list = list(dog_object_list) + list(breed_object_list)
        return object_list


class DogCreateView(LoginRequiredMixin, CreateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create.html'
    extra_context = {
        'title': 'Добавить собаку'
    }
    success_url = reverse_lazy('dogs:dogs_list')

    def form_valid(self, form):
        if self.request.user.role != UserRoles.USER:
            raise PermissionDenied()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogDetailView(LoginRequiredMixin, DetailView):
    model = Dog
    template_name = 'dogs/detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        object_ = context_data['object']
        context_data['title'] = f'Подробная информация {object_}'
        dog_object_increase = get_object_or_404(Dog, pk=object_.pk)
        if object_.owner != self.request.user.role and self.request.user.role not in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            dog_object_increase.views_count()
        if object_.owner:
            object_owner_email = object_.owner.email
            if dog_object_increase.views % 20 == 0 and dog_object_increase.views != 0:
                send_views_email(dog_object_increase.name, object_owner_email, dog_object_increase.views)
        return context_data


class DogUpdateView(LoginRequiredMixin, UpdateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/update.html'

    def get_success_url(self):
        return reverse('dogs:dog_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and self.request.user.role != UserRoles.ADMIN:
            raise PermissionDenied
        return self.object

    def get_form_class(self):
        dog_forms = {
            UserRoles.ADMIN: DogAdminForm,
            UserRoles.MODERATOR: DogForm,
            UserRoles.USER: DogForm,
        }
        user_role = self.request.user.role
        dog_form_class = dog_forms[user_role]
        return dog_form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        DogParentFormset = inlineformset_factory(Dog, DogParent, form=DogParentForm, extra=1)
        if self.request.method == 'POST':
            formset = DogParentFormset(self.request.POST, instance=self.object)
        else:
            formset = DogParentFormset(instance=self.object)
        object_ = context_data['object']
        context_data['title'] = f'Изменить собаку {object_}'
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class DogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Dog
    template_name = 'dogs/delete.html'
    success_url = reverse_lazy('dogs:dogs_list')
    permission_required = 'dogs.delete_dog'
    permission_denied_message = 'У вас нет нужных прав для данного действия'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        object_ = context_data['object']
        context_data['title'] = f'Удалить собаку {object_}'
        return context_data


def dog_toggle_activity(request, pk):
    dog_item = get_object_or_404(Dog, pk=pk)
    if dog_item.is_active:
        dog_item.is_active = False
    else:
        dog_item.is_active = True
    dog_item.save()
    return redirect(reverse('dogs:dogs_list'))

dogs/templates/dogs/includes/inc_breed.html
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <p class="card-text">{{ object.name }}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{% url 'dogs:breed_dogs' object.pk %}" type="button"
             class="btn btn-sm btn-outline-secondary">К собакам</a>
        </div>
      </div>
    </div>
  </div>
</div>

dogs/templates/dogs/includes/inc_dog_card.html
{% load my_tags %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
        </div>
        <img class="card-img-top"
            src="{{ object.photo|dogs_media }}" width="300" height="320"
            alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title pricing-card-title">Порода: {{ object.breed }}</h5>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Дата рождения: {{object.birth_date|default:'не известно'}}</li>
            </ul>
            <a class="btn btn-lg btn-block btn-outline-info"
            href="{% url 'dogs:dog_detail' object.pk %}">Информация</a>
            {% if user.is_authenticated and object.owner == user or user.role == 'admin' %}
            <a class="btn btn-lg btn-block btn-outline-warning"
               href="{% url 'dogs:dog_update' object.pk %}">
                {% if user.role == 'admin' %}
                Изменить/Удалить
                {% elif object.owner == user %}
                Изменить
                {% endif %}
            </a>
            {% endif %}
        </div>
    </div>
</div>

dogs/templates/dogs/includes/inc_pagination.html
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
    </li>
    {% else %}
    <li class="page_item disabled">
        <a class="page-link">&laquo;</a>
    </li>
    {% endif %}
    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active">
                <a class="page-link">{{ i }}<span class="sr-only">(current)</span></a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
    {% else %}
        <li class="page_item disabled">
            <a class="page-link">&raquo;</a>
        </li>
    {% endif %}
</ul>
{% endif %}

dogs/templates/dogs/includes/inc_search_breed_dog_fields.html
<form action="{% url 'dogs:breed_dog_search' %}" method="get">
    <input name="q" type="text" placeholder="Поиск">
</form>

dogs/templates/dogs/includes/inc_search_breed_fields.html
<form action="{% url 'dogs:breed_search' %}" method="get">
    <input name="q" type="text" placeholder="Поиск породы собак">
</form>

dogs/templates/dogs/includes/inc_search_dog_fields.html
<form action="{% url 'dogs:dogs_search' %}" method="get">
    <input name="q" type="text" placeholder="Поиск собаки по кличке">
</form>