config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

from dogs.views import index_view, BreedsListView, DogBreedListView, DogListView, DogCreateView, \
    DogDetailView, DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, BreedDogSearchListView, DogSearchListView, BreedSearchListView

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', cache_page(1)(index_view), name='index'),
    path('breeds/', cache_page(1)(BreedsListView.as_view()), name='breeds'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breed_search'),
    path('breeds/search_all/', BreedDogSearchListView.as_view(), name='breed_dog_search'),

    # dogs
    path('breeds/<int:pk>/dogs', DogBreedListView.as_view(), name='breed_dogs'),
    path('dogs/', DogListView.as_view(), name='dogs_list'),
    path('dogs/deactivated/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

reviews/urls.py
from django.urls import path
from reviews.apps import ReviewsConfig

from reviews.views import ReviewListView, ReviewDeactivatedListView, ReviewCreateView, ReviewDetailView, ReviewUpdateView, ReviewDeleteView, review_toggle_activity

app_name = ReviewsConfig.name

urlpatterns = [
    path('', ReviewListView.as_view(), name='reviews_list'),
    path('deactivated/', ReviewDeactivatedListView.as_view(), name='reviews_deactivated_list'),
    path('create/', ReviewCreateView.as_view(), name='review_create'),
    path('detail/<slug:slug>/', ReviewDetailView.as_view(), name='review_detail'),
    path('update/<slug:slug>/', ReviewUpdateView.as_view(), name='review_update'),
    path('delete/<slug:slug>/', ReviewDeleteView.as_view(), name='review_delete'),
    path('toggle/<slug:slug>/', review_toggle_activity, name='review_toggle'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserLogautView, UserUpdateVIEW, UserPasswordChangeView, user_generate_new_password_view, UserListView, UserDetailView


app_name = UsersConfig.name

urlpatterns = [
                # Работа с аккаунтом
                path('', UserLoginView.as_view(), name='user_login'),
                path('logout/', UserLogautView.as_view(), name='user_logout'),
                path('register/', UserRegisterView.as_view(), name='user_register'),
                path('profile/', UserProfileView.as_view(), name='user_profile'),
                path('update/', UserUpdateVIEW.as_view(), name='user_update'),
                path('change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
                path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),
                # Просмотр других пользователей
                path('all_users/', UserListView.as_view(), name='users_list'),
                path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail')
]

dogs/models.py
from django.db import models
from django.conf import settings


from users.models import NULLABLE


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')
    description = models.CharField(max_length=1000, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'


class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='Фотография')
    birth_date = models.DateField(**NULLABLE, verbose_name='Дата рождения')
    is_active = models.BooleanField(default=True, verbose_name='Активность')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Хозяин')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.name} ({self.breed})'

    class Meta:
        verbose_name = 'dog'
        verbose_name_plural = 'dogs'

    def views_count(self):
        self.views += 1
        self.save()


class DogParent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, verbose_name='Кличка родителя')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода родителя')
    birth_day = models.DateField(**NULLABLE, verbose_name='Дата рождения родителя')

    def __str__(self):
        return f'{self.name} ({self.breed})'

    class Meta:
        verbose_name = 'parent'
        verbose_name_plural = 'parents'

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog, DogParent
from users.forms import StyleFormMixin


class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        exclude = ('owner', 'is_active', 'views', )

    def clean_birth_date(self):
        cleaned_data = self.cleaned_data['birth_date']
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 35:
            raise forms.ValidationError('Собака должна быть моложе 35 лет')
        return cleaned_data


class DogAdminForm(DogForm):
    class Meta:
        model = Dog
        exclude = ('is_active',)


class DogParentForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = DogParent
        fields = '__all__'

dogs/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from dogs.models import Breed, Dog, DogParent
from dogs.forms import DogForm, DogParentForm, DogAdminForm
from dogs.services import send_views_email
from users.models import UserRoles


def index_view(request):
    context = {
        'object_list': Breed.objects.all()[:3],
        'title': 'Питомник - Главная'
    }
    return render(request, 'dogs/index.html', context=context)


class BreedsListView(ListView):
    model = Breed
    extra_context = {
        'title': 'Все наши породы'
    }
    template_name = 'dogs/breeds.html'
    paginate_by = 3


class BreedSearchListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'dogs/breeds.html'
    extra_context = {
        'title': 'Результат поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Breed.objects.filter(Q(name__icontains=query))
        return object_list


class DogBreedListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dogs.html'
    extra_context = {
        'title': 'Собаки выбранной породы'
    }

    def get_queryset(self):
        queryset = super().get_queryset().filter(breed_id=self.kwargs.get('pk'))
        return queryset


class DogListView(ListView):
    model = Dog
    extra_context = {
        'title': 'Питомник - все наши собаки'
    }
    template_name = 'dogs/dogs.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class DogDeactivatedListView(LoginRequiredMixin, ListView):
    model = Dog
    extra_context = {
        'title': 'Питомник - все наши собаки'
    }
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.role in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            queryset = queryset.filter(is_active=False)
        if self.request.user.role == UserRoles.USER:
            queryset = queryset.filter(is_active=False, owner=self.request.user)
        return queryset


class DogSearchListView(LoginRequiredMixin, ListView):
    model = Dog
    template_name = 'dogs/dog_search_results.html'
    extra_context = {
        'title': 'Результат поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Dog.objects.filter(
            Q(name__icontains=query, is_active=True)
        )
        return object_list


class BreedDogSearchListView(LoginRequiredMixin, ListView):
    model = Breed
    template_name = 'dogs/breed_dog_search_results.html'
    extra_context = {
        'title': 'Результаты поиска'
    }

    def get_queryset(self):
        query = self.request.GET.get('q')
        dog_object_list = Dog.objects.filter(
            Q(name__icontains=query, is_active=True)
        )
        breed_object_list = Breed.objects.filter(
            Q(name__icontains=query)
        )
        object_list = list(dog_object_list) + list(breed_object_list)
        return object_list


class DogCreateView(LoginRequiredMixin, CreateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/create.html'
    extra_context = {
        'title': 'Добавить собаку'
    }
    success_url = reverse_lazy('dogs:dogs_list')

    def form_valid(self, form):
        if self.request.user.role != UserRoles.USER:
            raise PermissionDenied()
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class DogDetailView(LoginRequiredMixin, DetailView):
    model = Dog
    template_name = 'dogs/detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        object_ = context_data['object']
        context_data['title'] = f'Подробная информация {object_}'
        dog_object_increase = get_object_or_404(Dog, pk=object_.pk)
        if object_.owner != self.request.user.role and self.request.user.role not in [UserRoles.ADMIN, UserRoles.MODERATOR]:
            dog_object_increase.views_count()
        if object_.owner:
            object_owner_email = object_.owner.email
            if dog_object_increase.views % 20 == 0 and dog_object_increase.views != 0:
                send_views_email(dog_object_increase.name, object_owner_email, dog_object_increase.views)
        return context_data


class DogUpdateView(LoginRequiredMixin, UpdateView):
    model = Dog
    form_class = DogForm
    template_name = 'dogs/update.html'

    def get_success_url(self):
        return reverse('dogs:dog_detail', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and self.request.user.role != UserRoles.ADMIN:
            raise PermissionDenied
        return self.object

    def get_form_class(self):
        dog_forms = {
            UserRoles.ADMIN: DogAdminForm,
            UserRoles.MODERATOR: DogForm,
            UserRoles.USER: DogForm,
        }
        user_role = self.request.user.role
        dog_form_class = dog_forms[user_role]
        return dog_form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        DogParentFormset = inlineformset_factory(Dog, DogParent, form=DogParentForm, extra=1)
        if self.request.method == 'POST':
            formset = DogParentFormset(self.request.POST, instance=self.object)
        else:
            formset = DogParentFormset(instance=self.object)
        object_ = context_data['object']
        context_data['title'] = f'Изменить собаку {object_}'
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class DogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Dog
    template_name = 'dogs/delete.html'
    success_url = reverse_lazy('dogs:dogs_list')
    permission_required = 'dogs.delete_dog'
    permission_denied_message = 'У вас нет нужных прав для данного действия'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        object_ = context_data['object']
        context_data['title'] = f'Удалить собаку {object_}'
        return context_data


def dog_toggle_activity(request, pk):
    dog_item = get_object_or_404(Dog, pk=pk)
    if dog_item.is_active:
        dog_item.is_active = False
    else:
        dog_item.is_active = True
    dog_item.save()
    return redirect(reverse('dogs:dogs_list'))

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        {% if user.role == 'admin' %}
                        <a class="p-2 btn btn-success" href="/admin/">Админка</a>
                        {% endif %}
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:breeds' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:dogs_list' %}" class="text-white">Собаки</a></li>
                        <li><a href="{% url 'reviews:reviews_list' %}" class="text-white">Наши отзывы</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:users_list' %}" class="text-white">Все пользователи</a></li>
                        <form method="post" action="{% url 'users:user_logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Выход</button>
                        </form>
                        {% else %}
                            <li><a href="{% url 'users:user_login' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:user_register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
                {% if user.is_authenticated %}
                <span class="text-white"  style="margin-left: 50px">{{ user }}</span>
                {% endif %}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/breed_dog_search_results.html
{% extends 'dogs/base.html'%}
{% load my_tags %}
{% block content %}
{% include 'dogs/includes/inc_search_dog_fields.html' %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}

</div>
{% endblock %}

dogs/templates/dogs/breeds.html
{% extends 'dogs/base.html' %}

{% block content %}
{% include 'dogs/includes/inc_search_breed_fields.html' %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object %}
    {% endfor %}
</div>
{% include 'dogs/includes/inc_pagination.html' %}
{% endblock %}

dogs/templates/dogs/create.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Обновите данные собаки
                {% else %}
                Введите данные собаки
                {% endif %}
            </div>
            <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="400"
                 alt="Card image cap">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/create_update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Обновите данные собаки
                {% else %}
                Введите данные собаки
                {% endif %}
            </div>
            <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="400"
                 alt="Card image cap">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
        <div class="card-header">
            {% if object %}
            Вы уверены, что хотите удалить собаку?
            {% endif %}
        </div>
    </div>
        <div class="card-body">
            <img class="card_img_top"
            src="{{ object.photo|dogs_media }}" width="348" height="320"
            alt="Card image cap">
        </div>
        <div class="card-body">
            <p class="card-text">{{ object.name|title }}</p>
        </div>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-danger float-right">
            {% if object %}
            Удалить
            {% endif %}
        </button>
        <a class="btn btn-outline-dark float-left" href="{%  url 'dogs:dog_detail' object.pk %}">Назад</a>
    </div>
</form>


{% endblock %}

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col=md-4">
    <div class="card mb-4 box-shadow">
        <img class="card_img_top"
            src="{{ object.photo|dogs_media }}" width="300" height="320"
            alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Кличка: {{ object.name }}</p>
            <p class="card-text">Порода: {{ object.breed.name }}</p>
            <span class="text-muted">Дата рождения:{{ object.birth_date|default:"-"}}</span><br>
            <span class="text-muted">Эл. почта хозяина: {{ object.owner|default:"Без хозяина" }}</span><br>
            <span class="text-muted">Имя хозяина: {{ object.owner.first_name|default:"Не указано" }}</span><br>
            <span class="text-muted">Телефон хозяина: {{ object.owner.phone|default:"Не указано" }}</span><br>
            <span class="text-muted">Телеграм хозяина: {{ object.owner.telegram|default:"Не указано" }}</span><br>
            <span class="text-muted">Просмотры: {{ object.views }}</span>
        </div>
        <div class="card-footer">
            <a class="btn btn-link" href="{%  url 'dogs:dog_update' object.pk %}">обновить</a>
            <a class="btn btn-link" href="{%  url 'dogs:dog_delete' object.pk %}">удалить</a>
        </div>
    </div>
</div>

{% endblock %}

dogs/templates/dogs/dog_search_results.html
{% extends 'dogs/base.html'%}
{% load my_tags %}
{% block content %}
{% include 'dogs/includes/inc_search_breed_dog_fields.html' %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    {% include 'dogs/includes/inc_pagination.html' %}
    <a href="{% url 'dogs:dog_create' %}" class="btn btn-outline-primary m-2 float-left">Добавить собаку</a>
    <a href="{% url 'dogs:dogs_deactivated_list' %}" class="btn btn-outline-secondary m-2 float-right">Неактивные собаки</a>
    <a href="{% url 'dogs:dogs_list' %}" class="btn btn-outline-success m-2 float-right">Активные собаки</a>
</div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="continer">
    <div class="row">
        {% for object in object_list %}
        {% include 'dogs/includes/inc_dog_card.html' with object=object %}
        {% endfor %}
    </div>
    <a href="{% url 'dogs:dogs_list' %}" class="btn btn-outline-success m-2">Активные собаки</a>
    <a href="{% url 'dogs:dogs_deactivated_list' %}" class="btn btn-outline-secondary m-2">Неактивные собаки</a>
</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Обновите данные собаки
                {% else %}
                Введите данные собаки
                {% endif %}
            </div>
            <img class="card-img-top"
                 src="{{ object.photo|dogs_media }}" width="300" height="400"
                 alt="Card image cap">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
               <input type="submit" class="btn btn-outline-success"
                      value="{% if object %}Сохранить{% else %}Добавить{% endif %}">
                <a href="{% url 'dogs:dog_toggle_activity' object.pk %}"
                   class="btn btn-outline-warning float-right">
                    {% if object.is_active %}
                    Деактивировать
                    {% else %}
                    Активировать
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'dogs:dogs_list' %}" class="btn btn-outline-primary"><< Назад</a>
            {% if object and user.is_superuser %}
            <a href="{% url 'dogs:dog_delete' object.pk %}" class="btn btn-outline-danger float-right">Удалить</a>
            {% endif %}
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}