config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig
from django.views.decorators.cache import cache_page, never_cache

from dogs.views import index_view, BreedsListView, DogBreedListView, DogListView, DogCreateView, \
    DogDetailView, DogUpdateView, DogDeleteView, DogDeactivatedListView, dog_toggle_activity, BreedDogSearchListView, DogSearchListView, BreedSearchListView

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', cache_page(1)(index_view), name='index'),
    path('breeds/', cache_page(1)(BreedsListView.as_view()), name='breeds'),
    path('breeds/search/', BreedSearchListView.as_view(), name='breed_search'),
    path('breeds/search_all/', BreedDogSearchListView.as_view(), name='breed_dog_search'),

    # dogs
    path('breeds/<int:pk>/dogs', DogBreedListView.as_view(), name='breed_dogs'),
    path('dogs/', DogListView.as_view(), name='dogs_list'),
    path('dogs/deactivated/', DogDeactivatedListView.as_view(), name='dogs_deactivated_list'),
    path('dogs/search/', DogSearchListView.as_view(), name='dogs_search'),
    path('dogs/create/', DogCreateView.as_view(), name='dog_create'),
    path('dogs/detail/<int:pk>/', DogDetailView.as_view(), name='dog_detail'),
    path('dogs/update/<int:pk>/', never_cache(DogUpdateView.as_view()), name='dog_update'),
    path('dogs/toggle/<int:pk>/', dog_toggle_activity, name='dog_toggle_activity'),
    path('dogs/delete/<int:pk>/', DogDeleteView.as_view(), name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView, UserLoginView, UserProfileView, UserLogautView, UserUpdateVIEW, UserPasswordChangeView, user_generate_new_password_view, UserListView, UserDetailView


app_name = UsersConfig.name

urlpatterns = [
                # Работа с аккаунтом
                path('', UserLoginView.as_view(), name='user_login'),
                path('logout/', UserLogautView.as_view(), name='user_logout'),
                path('register/', UserRegisterView.as_view(), name='user_register'),
                path('profile/', UserProfileView.as_view(), name='user_profile'),
                path('update/', UserUpdateVIEW.as_view(), name='user_update'),
                path('change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
                path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),
                # Просмотр других пользователей
                path('all_users/', UserListView.as_view(), name='users_list'),
                path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


NULLABLE = {'blank': True, 'null': True}


class UserRoles(models.TextChoices):
    ADMIN = 'admin', _('admin')
    MODERATOR = 'moderator', _('moderator')
    USER = 'user', _('user')


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    role = models.CharField(max_length=9, choices=UserRoles.choices, default=UserRoles.USER)
    first_name = models.CharField(max_length=150, verbose_name='Имя', default='Anonymous')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', default='Anonymous')
    phone = models.CharField(max_length=35, unique=True, verbose_name='Телефон', **NULLABLE)
    telegram = models.CharField(max_length=150, unique=True, verbose_name='Телеграм', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']

users/forms.py
from django import forms

from users.models import User
from users.validators import validate_password
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar',)


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    # password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    # password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        validate_password(cleaned_data['password1'])
        if cleaned_data['password1'] != cleaned_data['password2']:
            print('Пароли не совпадают!')
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch'
            )
        return cleaned_data['password2']


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    pass
    # email = forms.EmailField()
    # password = forms.CharField(label='Пароль', widget=forms.PasswordInput)


class UserUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)


class UserPasswordChangeForm(StyleFormMixin, PasswordChangeForm):
    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        validate_password(password2)
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch'
            )
        password_validation.validate_password(password2, self.user)
        return password2

users/views.py
import random
import string

from django.shortcuts import reverse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, PasswordChangeView, LogoutView
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from users.models import User
from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserPasswordChangeForm, UserForm
from users.services import send_register_email, send_new_password


class UserRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:user_login')
    template_name = 'users/user_register.html'
    extra_context = {
        'title': 'Создать аккаунт'
    }

    def form_valid(self, form):
        self.object = form.save()
        send_register_email(self.object.email)
        return super().form_valid(form)


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'users/user_login.html'
    extra_context = {
        'title': 'Вход в аккаунт'
    }


class UserProfileView(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'users/user_profile_read_only.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['title'] = f'Ваш профиль {self.get_object()}'
        return context_data


class UserUpdateVIEW(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/user_update.html'
    success_url = reverse_lazy('users:user_profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['title'] = f'Обновить профиль {self.get_object()}'
        return context_data


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/user_password_change.html'
    success_url = reverse_lazy('users:user_profile')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['title'] = f'Изменить пароль {self.request.user}'
        return context_data


class UserLogautView(LogoutView):
    template_name = 'users/user_logout.html'
    extra_context = {
        'title': 'Выход из аккаунта'
    }


class UserListView(LoginRequiredMixin, ListView):
    model = User
    extra_context = {
        'title': 'Питомник все наши пользователи'
    }
    template_name = 'users/users.html'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class UserDetailView(DetailView):
    model = User
    template_name = 'users/user_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        user_obj = context_data['object']
        # user_obj = self.get_object()
        context_data['title'] = f'Профиль пользователя {user_obj}'
        return context_data


@login_required(login_url='users:user_login')
def user_generate_new_password_view(request):
    new_password = ''.join(random.sample((string.ascii_letters + string.digits), 12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/users/user_change_password.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="card">
      <div class="card-header">
        Изменение пароля
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {{ form.as_p }}
          <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'dogs/base.html' %}
{% load my_tags%}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Профиль {{ object.first_name }} {{ object.last_name }}
                </div>
                <img class="card-img-top"
                    src="{{ object.avatar|user_media}}" width="100%"
                    alt="Card image cap">
                <div class="card-body">
                    <span class="card-text">Почта: {{ object.email }}</span><br>
                    <span class="card-text">Имя: {{ object.first_name|default:"Не указано" }}</span><br>
                    <span class="card-text">Фамилия: {{ object.last_name|default:"Не указано" }}</span><br>
                    <span class="card-text">Телефон: {{ object.phone|default:"Не указано" }}</span><br>
                    <span class="card-text">Телеграмм: {{ object.telegram|default:"Не указано" }}</span><br>
                </div>
                <div class="card-footer">
                    <a href="{% url 'users:users_list' %}" class="btn btn-outline-primary"><< Назад</a>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

users/templates/users/user_login.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Введите данные для входа в аккаунт</div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success float-right">Войти</button>
                        </form>
                    </div>
                <div class="card-footer"></div>
            </div>
        </div>
</div>
{% endblock %}

users/templates/users/user_logout.html
{% extends 'dogs/base.html' %}
{% block content %}
<h1> Вы вышли из вашего аккаунта</h1>
<p>Спасибо зи использование нашего сервиса</p>
<a href="{% url 'users:user_login' %}">Нажмите чтобы снова войти</a>
{% endblock %}

users/templates/users/user_password_change.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="card">
      <div class="card-header">
        Изменение пароля
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
           {% csrf_token %}
           {{ form.as_p }}
          <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/user_profile_read_only.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <img class="card-img-top"
                src="{{ user.avatar|user_media }}" width="100%"
                alt="Card image cap">
            <div class="card-body">
                <span class="card-text">Email: {{user.email}}</span><br>
                <span class="card-text">Имя: {{user.first_name|default:"не указано"}}</span><br>
                <span class="card-text">Фамилия: {{user.last_name|default:"не указано"}}</span><br>
                <span class="card-text">Телефон: {{user.phone|default:"не указано"}}</span><br>
                <span class="card-text">Телеграм: {{user.telegram|default:"не указано"}}</span><br>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_update' %}">обновить</a>
                </button>
                 <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_change_password' %}">изменить пароль</a>
                </button>
                <button class="btn btn-outline-danger">
                    <a class="btn btn-link" href="{% url 'users:user_generate_new_password' %}">генерация пароля</a>
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_register.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Введите необходимые данные</div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success float-right">Регистрация</button>
                        </form>
                    </div>
            </div>
        </div>
</div>
{% endblock %}

users/templates/users/user_update.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="card">
      <div class="card-header">
        Изменить профиль
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/users.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
        {% include 'users/includes/inc_user_card.html' with object=object %}
        {% endfor %}
    </div>
</div>
{% endblock%}